language: php

php:
    - "5.4"

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository -y ppa:gearman-developers/ppa
    - sudo apt-get update
    - sudo apt-get install -qq gearman-job-server libgearman-dev gearman-tools
    - sudo apt-get install php-pear
    - pecl install gearman
    - make
    - mysql -e 'create database thinkup_crawl_manager;'
    - mysql -u root thinkup_crawl_manager < sql/setup.sql

script:
    - ./bin/testrunner --tap tests/